apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: platformforge-discord
  namespace: monitoring

  labels:
    release: monitoring

spec:
  route:
    receiver: discord

  receivers:
    - name: discord

      webhookConfigs:
        - urlSecret:
            name: discord-webhook
            key: url