apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: platformforge

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: apurvaborhade/platformforge-backend:latest


          ports:
            - containerPort: 3001

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "200m"